version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: estacionamento-db
    environment:
      POSTGRES_DB: estacionamento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: estacionamento-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estacionamento
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: senha
    ports:
      - "8080:8080"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: estacionamento-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
```
