
---
- name: Cleanup da aplicação no Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_name: "{{ cluster_name }}"
    cluster_location: "{{ cluster_location }}"
    project_id: "celtic-shape-452222-c9"
    namespace: "estacionamento"

  tasks:
    - name: Configurar kubectl para conectar ao cluster GKE
      shell: |
        gcloud container clusters get-credentials {{ cluster_name }} \
          --location {{ cluster_location }} \
          --project {{ project_id }}

    - name: Remover todos os recursos do namespace
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        wait: true
        wait_timeout: 300

    - name: Confirmar limpeza
      debug:
        msg: |
          Limpeza concluída com sucesso!
          Namespace '{{ namespace }}' e todos os recursos foram removidos.
