name: CI Pipeline
 
on:
  push:
    branches: [ docker-build ]
  pull_request:
    branches: [ docker-build ]

jobs:
  terraform:
    name: Provisionar infraestrutura com Terraform
    runs-on: ubuntu-latest
    env:
      GCP_USER: ${{ secrets.GCP_USER }}
      SSH_KEY_PUB: ${{ secrets.SSH_KEY_PUB }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Criar arquivo de credenciais do GCP
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > ${{ github.workspace }}/ansible/credentials.json

      - name: Configurar variável de autenticação
        run: export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/ansible/credentials.json

      - name: Executar Terraform
        working-directory: ansible
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/ansible/credentials.json
        run: |
          terraform init
          terraform import \
            -var="gcp_user=$GCP_USER" \
            -var="ssh_key_pub=$SSH_KEY_PUB" \
            google_compute_instance.vm projects/celtic-shape-452222-c9/zones/southamerica-east1-a/instances/vm-aplicacao
          terraform import \
            -var="gcp_user=$GCP_USER" \
            -var="ssh_key_pub=$SSH_KEY_PUB" \
            google_compute_firewall.firewall projects/celtic-shape-452222-c9/global/firewalls/allow-ssh-and-app
          terraform apply -auto-approve \
            -var="gcp_user=$GCP_USER" \
            -var="ssh_key_pub=$SSH_KEY_PUB"

      - name: Obter IP da VM
        working-directory: ansible
        id: pegar_ip
        run: |
          echo "vm_ip=$(terraform output -raw vm_ip_address)" >> $GITHUB_OUTPUT
          
    outputs:
      vm_ip: ${{ steps.pegar_ip.outputs.vm_ip }}

  ansible:
    name: Configurar VM com Ansible
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Criar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Criar inventário
        run: |
          echo "${{ needs.terraform.outputs.vm_ip }} ansible_user=${{ secrets.GCP_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" > ansible/inventory.ini

      - name: Executar Ansible
        run: |
          ansible-playbook -i ansible/hosts/inventory.ini ansible/playbooks/playbook.yml \
            -e "docker_user=${{ secrets.DOCKER_USERNAME }} docker_password=${{ secrets.DOCKER_PASSWORD }}"
